sudo: required
git:
    submodules: false
before_install:
 - sudo apt-get install python3-dev
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
language: rust
rust:
  - stable
  - beta
  - nightly
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  allow_failures:
    - rust: nightly
