sudo: required
git:
    submodules: false
before_install:
 - sudo apt-get update
 - sudo apt-get install python3
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    sources: ['pythonxy-devel']
    packages:
    - python-dev
    - python3-dev
matrix:
  allow_failures:
    - rust: nightly
