[package]
name = "rori_server"
version = "0.0.0"
authors = ["AmarOk <amarok@enconn.fr>"]

[dependencies]
rustc-serialize = "*"
regex = "*"
lazy_static = "*"
iron = "*"
router = "*"
hyper = "*"
log = "*"
env_logger = "*"
